name: Lighthouse Check
on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Audit Lighthouse + Génération de badge
      - name: Audit Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://lectures-du-jour.vercel.app/
          uploadTargets: 'temporary-public-storage'
