name: Lighthouse CI
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Audit Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://lectures-du-jour.vercel.app/
          temporaryPublicStorage: true
